# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "rac1-endirecte"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Josep Sirvent"]
  s.date = "2013-02-09"
  s.description = "Escoltar RAC1 en directe des de la terminal"
  s.email = "apuratepp@gmail.com"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.homepage = "http://github.com/apuratepp/rac1-endirecte"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Escoltar RAC1 en directe des de la terminal"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

